### ISSUE TITLE
Bug: Change on handleGetNetworkHashPS() to return float64 breaks rpcclient code

### ISSUE THREAD

**Issue by swdee** [gcash/bchd#112] opened 2018-11-06 00:36 UTC
In the following two commits 0ef2e3376a87d11d4cb59af6c59fbb0902f124bd and e53631212be2afc65c875cb97ada0a99a2f2c7a4 the handleGetNetworkHashPS() function was changed from the upstream source to return a float64 instead of the expected int64.

As explicitly stated in the code comments this function returns an interface{} but all values returned should be int64.  By returning a float64 the rpcclient code is now broken https://github.com/gcash/bchd/blob/a3262a23a67871fa552025111b2bbd65fb48b80c/rpcclient/mining.go#L218 and terminates at run time due to it failing to unmarshal the JSON.

```
json: cannot unmarshal number 181192779577.548 into Go value of type int64
exit status 1
```

Can someone provide some insight as to why this was changed to float64?

**Comment by swdee** [comment] 2018-11-06 00:38
Looks like the description in an earlier attempt to change this explains the issue fda11e6f9fb7ca288f5cc8c384ddc13b34441cc0

**Comment by swdee** [comment] 2018-11-06 00:40
With PR here for reference https://github.com/gcash/bchd/pull/44

**Comment by zquestz** [comment] 2018-11-06 00:47
Good catch, any chance you can fix the rpcclient to support this? Seems like just a reflection addition.

**Comment by zquestz** [comment] 2018-11-06 00:48
Either that or we can revert the previous change and have @romainPellerin take a closer look at it.

**Comment by zquestz** [comment] 2018-11-06 01:28
Thank you! The issue is just the fact it is represented as `4.605279037985576e+18` which is an integer, but not parsable as a uint64... Thanks for looking into this. Greatly appreciated. =)

**Comment by zquestz** [comment] 2018-11-06 05:14
Fix merged. Thanks @swdee

**Closed by zquestz** 2018-11-06 05:14 UTC
Labels: bug
