### ISSUE TITLE
BCHD Node fell out of sync: block 579591

### ISSUE THREAD

**Issue by JettScythe** [gcash/bchd#220] opened 2019-04-27 00:01 UTC
So, I'm not entirely sure what happened but I noticed my node fell out of sync and was just adding orphan blocks. It hung up entirely with `[INF] SYNC: Rejected block 0000000000000000024d3b3cc838106cd1662d3b7455b2336c3d341f8a560ac4 from 47.254.30.182:8333 (outbound): previous block 000000000000000000ed4072fbbd8396d8f4ee9960410cd5475bf2ab0ed7b1d0 is known to be invalid`

`grep 000000000000000000ed4072fbbd8396d8f4ee9960410cd5475bf2ab0ed7b1d0 ~/.bchd/logs/mainnet/bchd.log` produces `2019-04-26 16:06:31.018 [INF] SYNC: Rejected block 0000000000000000024d3b3cc838106cd1662d3b7455b2336c3d341f8a560ac4 from 94.247.134.76:8333 (outbound): previous block 000000000000000000ed4072fbbd8396d8f4ee9960410cd5475bf2ab0ed7b1d0 is known to be invalid`
& `bchctl reconsiderblock 000000000000000000ed4072fbbd8396d8f4ee9960410cd5475bf2ab0ed7b1d0` produces `output ac2e33960a70c495cf4f781fa4ea217a772a0938b21ff78ce272d9e36b3b4635:10 referenced from transaction 010d95773d04f84019be67fb89e321d8d00f282597fd9a1111fd0657e5c9e631:0 does not exist`

Only fix I found was to delete the data folder and resync.

**Comment by cpacia** [comment] 2019-04-27 03:28
Was this a fast synced node?

**Comment by JettScythe** [comment] 2019-04-27 03:28
yup

**Comment by cpacia** [comment] 2019-04-27 03:34
Hmm. I just started up my fast sync node and it got past 579591 and made it to the tip. Did you have a hard shutdown of that node at any point in time?

**Comment by JettScythe** [comment] 2019-04-27 03:42
For sure. I think I had one the same day before I figured out how to use Screen in the terminal.

**Comment by cpacia** [comment] 2019-04-27 04:06
Well the problem is it should be able to recover from a hard shutdown by rolling back the chain and utxo to the last consistent state then rolling forward. 

This part of the code is extremely complex and as far as I can tell it is implemented correctly but maybe given the problem you had it isn't.

**Comment by slavomirtravica** [comment] 2019-04-28 07:58
I tried fixing my full node with: bchctl reconsiderblock 0000000000000000001df2299a0d705bc95df7045398a32d1dea5ccff7bb9fb6

But getting this:
Post https://localhost:8334: dial tcp [::1]:8334: connectex: No connection could be made because the target machine actively refused it.

Using "netstat -aon" command I can't see port currently used and I added it to windows firewall rules.
Tried meddling bchd.cof but it bore no fruit either.
See that people get it for variety of reasons, so id anyone else had it, I'd appreciate if you could share how you solved it.

**Comment by JettScythe** [comment] 2019-04-28 15:26
Bchctl has it's own .conf file. Make sure both bchctl & bchd have the same credentials for the RPCuser

**Comment by nshopik** [comment] 2019-05-22 12:33
I've actually got in same situation but different block 
```
Rejected block 0000000000000000024578c467057df411eb72822dac836772164a27bed46a5b from 62.210.110.181:8333 (outbound): previous block 0000000000000000001df2299a0d705bc95df7045398a32d1dea5ccff7bb9fb6 is known to be invalid
```

**Comment by zquestz** [comment] 2019-06-19 08:18
> I've actually got in same situation but different block
> 
> ```
> Rejected block 0000000000000000024578c467057df411eb72822dac836772164a27bed46a5b from 62.210.110.181:8333 (outbound): previous block 0000000000000000001df2299a0d705bc95df7045398a32d1dea5ccff7bb9fb6 is known to be invalid
> ```
> 
> and reconsider block just complain
> `block 0000000000000000024578c467057df411eb72822dac836772164a27bed46a5b is not know`

You just want to run `bchctl reconsiderblock 0000000000000000001df2299a0d705bc95df7045398a32d1dea5ccff7bb9fb6`

Need to make sure to reconsider the known bad block, not the block it rejected.

**Comment by zquestz** [comment] 2019-07-21 03:16
Going to close this. If anyone experiences this issue again we can reopen.

**Closed by zquestz** 2019-07-21 03:16 UTC

**Comment by rained23** [comment] 2019-11-29 12:00
I receive this issue while running fastsync on my docker
```
bchd    | 2019-11-29 11:57:46.629 [INF] SYNC: Rejected block 000000000000000001fc3c040657699fa658c53da239dcd1db7a203086a0c243 from 128.199.138.39:8333 (outbound): previous block 000000000000000000fae770b025a5f763ce3afb8a6b394fb6082dcb385e3c9d is known to be invalid

```

```
docker exec bchd bchctl reconsiderblock 000000000000000000fae770b025a5f763ce3afb8a6b394fb6082dcb385e3c9d
-32603: output f26a1c6af7095a0866a1125edbd92c5eb40e3a1f11ba1400f914a5fbfa66bfd4:1 referenced from transaction 03a294bbd91c9f7154795470a0c2bd1549471810eca04f5290bbc71968dc1846:0 does not exist
```

**Comment by merc1er** [comment] 2020-02-14 17:11
Same issue here (pruned node on ARM).

```shell
$ ./bchctl reconsiderblock 0000000000000089321cb7500b0173a3fb62669813b57de0d4f5c6e5eb2adc22
-32603: output c52b41a6f0dae4af908511664483d0cec62903b1f485322d45c6279c66c659e8:1 referenced from transaction 45328fe7961cc6c218b700df6962cf96a3078e561d81452f5a0bafd77de6ac8d:0 does not exist
```
